/* lex.c - Test case for lexer.
 * Copyright (C) 2022 epoll-reactor <glibcxx.chrono@gmail.com>
 *
 * This file is distributed under the MIT license.
 */

#include <stdio.h>

extern FILE *yyin;
extern int yylex();

int main() {
    /// Generated by flex code call lex_get_token() inside for each acceptable token.
    yyin = fopen("/home/fuck/weak_compiler/tests/front_end/input/parser/array_decl.wl", "r");
    yylex();
}