/* lex.h - flex-based lexical analyzer.
 * Copyright (C) 2022 epoll-reactor <glibcxx.chrono@gmail.com>
 *
 * This file is distributed under the MIT license.
 */

#ifndef WEAK_COMPILER_FRONTEND_LEX_LEX_H
#define WEAK_COMPILER_FRONTEND_LEX_LEX_H

#include "front_end/lex/tok.h"

/// This function is called inside file, generated by flex on
/// each processed token. May be used for example to collect
/// all tokens into some array.
void lex_get_token(tok_t *tok);

#endif // WEAK_COMPILER_FRONTEND_LEX_LEX_H